version: "3"

# docker network create chatbot

services:
  mongo:
    container_name: mongo_chatbot
    image: mongo:latest
    restart: always
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth
    networks:
      - chatbot

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - chatbot

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    # ports:
    #   - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_chatbot
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=chatbot
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - chatbot

networks:
  chatbot:
    external: True